local Set = require('igit.datatype.Set')

describe("Constructor", function()
    it("Takes zero argument.", function()
        local s = Set()
        assert.are.same(s:size(), 0)
    end)

end)

describe("add", function()
    it("Sets value to true by default", function()
        local s = Set({'a', 'b'})
        s:add('c')
        assert.are.equal(s['c'], true)
    end)
    it("Respects optional value argument", function()
        local s = Set({'a', 'b'})
        s:add('c', 1)
        assert.are.equal(s['c'], 1)
    end)
    it("Does nothing if key presents", function()
        local s = Set({'a', 'b'})
        s:add('c', 1)
        assert.are.equal(s['c'], 1)
        s:add('c', 2)
        assert.are.equal(s['c'], 1)
    end)
end)

describe("remove", function()
    it("Removes element if present", function()
        local s = Set({'a', 'b'})
        s:remove('b')
        assert.falsy(s:has('b'))
    end)
    it("Does nothing if key is missing", function()
        local s = Set({'a', 'b'})
        s:remove('c')
        assert.are.equal(s:size(), 2)
    end)
end)

describe("has", function()
    it("Returns true if key presents", function()
        local s = Set({'a', 'b'})
        assert.truthy(s:has('a'))
        assert.truthy(s:has('b'))
    end)
    it("Returns false if key missing", function()
        local s = Set({'a', 'b'})
        assert.falsy(s:has('c'))
    end)
end)

describe("size", function()
    it("Returns the correct size", function()
        local s = Set({'a', 'b'})
        assert.are.equal(s:size(), 2)
        s = Set({'a', 'b', 'c'})
        assert.are.equal(s:size(), 3)
    end)
end)

describe("iter", function()
    it("Iteratrates through its values", function()
        local s = Set({1, 2, 3})
        local i = 1
        for e in s:iter() do
            assert.are.equal(i, e)
            i = i + 1
        end

    end)
end)
