local igit = require("igit.vcs.git")

describe("igit", function()
	it("Sets up its submodules", function()
		require("igit").register_vcs_module(igit, {})
		assert.is_truthy(igit.log)
		assert.is_truthy(igit.branch)
		assert.is_truthy(igit.status)
	end)
end)
